//------------------------------------------------------------------------------
// This file is AUTO-GENERATED by OKGamesLib.AssetAddressCodeGenerator.
//------------------------------------------------------------------------------
namespace OKGamesLib
{
    public static class AssetAddress {
      public enum AssetAddressEnum {
        onepiece02_zoro_bandana = 0,
        onepiece06_chopper      = 1,
        onepiece01_luffy        = 2,
        TapEffect               = 3,
        DebugManager            = 4,
        NowLoading              = 5,
        FadeCanvas              = 6,
        Fader                   = 7,
        PopNotify               = 8,
        CommonDialog            = 9,
        CommonDialogView        = 10,
        SystemDialogView        = 11,
        SystemDialog            = 12,
        CustomeDialog           = 13,
        NotoSansJP_Medium_SDF   = 14,
        NotoSans_Medium_SDF     = 15,
        onepiece07_robin        = 16,
        onepiece03_nami         = 17,
        param1                  = 18,
        texts                   = 19,
        platform_items          = 20,
        common_ng               = 21,
        common_ok               = 22,
        title_bgm               = 23,
        hiragana_01_a_png       = 24,
        hiragana_04_e_png       = 25,
        hiragana_05_o_png       = 26,
        hiragana_02_i_png       = 27,
        hiragana_03_u_png       = 28,
      }
    }
}
