//------------------------------------------------------------------------------
// This file is AUTO-GENERATED by OKGamesLib.AssetLabelCodeGenerator.
//------------------------------------------------------------------------------
namespace OKGamesLib
{
    public static class AssetLabel {
      public enum AssetLabelEnum {
        Boys                       = 0,
        CommonModule               = 1,
        DontDestroy                = 2,
        DontDestroy_PrefabInPrefab = 3,
        Font                       = 4,
        Girls                      = 5,
        MasterData                 = 6,
        Sound_SE                   = 7,
        UI                         = 8,
      }
    }
}
