//------------------------------------------------------------------------------
// This file is AUTO-GENERATED by OKGamesLib.AssetAddressCodeGenerator.
//------------------------------------------------------------------------------
namespace OKGamesLib {
    public static class AssetAddress {
        public enum AssetAddressEnum {
            onepiece02_zoro_bandana = 0,
            onepiece06_chopper = 1,
            onepiece01_luffy = 2,
            TapEffect = 3,
            DebugManager = 4,
            NowLoading = 5,
            GlobalContext = 6,
            FadeCanvas = 7,
            Fader = 8,
            NotoSansJP_Medium_SDF = 9,
            NotoSans_Medium_SDF = 10,
            onepiece07_robin = 11,
            onepiece03_nami = 12,
            param1 = 13,
            texts = 14,
            common_ng = 15,
            common_ok = 16,
            hiragana_01_a_png = 17,
            hiragana_04_e_png = 18,
            hiragana_05_o_png = 19,
            hiragana_02_i_png = 20,
            hiragana_03_u_png = 21,
        }
    }
}
