//------------------------------------------------------------------------------
// This file is AUTO-GENERATED by OKGamesLib.LayerMaskCodeGenerator.
//------------------------------------------------------------------------------
namespace OKGamesLib
{
    public static class LayerMasks {
      public enum LayerMasksEnum {
        Debug           = -2147483648,
        Default         = 1,
        TransparentFX   = 2,
        Ignore_Raycast  = 4,
        Water           = 16,
        UI              = 32,
        TransitionBoard = 256,
        NowLoading      = 512,
        Character       = 1024,
        TapEffect       = 2048,
      }
    }
}
