//------------------------------------------------------------------------------
// This file is AUTO-GENERATED by OKGamesLib.LayerNameCodeGenerator.
//------------------------------------------------------------------------------
namespace OKGamesLib
{
    public static class LayerName {
      public enum LayerNameEnum {
        Default         = 0,
        TransparentFX   = 1,
        Ignore_Raycast  = 2,
        Water           = 3,
        UI              = 4,
        TransitionBoard = 5,
        NowLoading      = 6,
        Character       = 7,
        TapEffect       = 8,
        Debug           = 9,
      }
    }
}
