//------------------------------------------------------------------------------
// This file is AUTO-GENERATED by OKGamesLib.LayerNameCodeGenerator.
//------------------------------------------------------------------------------
namespace OKGamesLib
{
    public static class LayerName {
      public enum LayerNameEnum {
        Default         = 0,
        TransparentFX   = 1,
        Ignore_Raycast  = 2,
        Water           = 3,
        UI              = 4,
        Dialog          = 5,
        PopText         = 6,
        TransitionBoard = 7,
        NowLoading      = 8,
        SystemDialog    = 9,
        Character       = 10,
        TapEffect       = 11,
        Debug           = 12,
      }
    }
}
