//------------------------------------------------------------------------------
// This file is AUTO-GENERATED by OKGamesLib.SceneNameCodeGenerator.
//------------------------------------------------------------------------------
namespace OKGamesLib
{
    public static class SceneName {
      public enum SceneNameEnum {
        Boot             = 0,
        TestCommonModule = 1,
        TestIAP          = 2,
        TestScroll       = 3,
        TitleScene       = 4,
      }
    }
}
