//------------------------------------------------------------------------------
// This file is AUTO-GENERATED by OKGamesLib.SceneNameCodeGenerator.
//------------------------------------------------------------------------------
namespace OKGamesLib
{
    public static class SceneName {
      public enum SceneNameEnum {
        TestBoot             = 0,
        TestIAP              = 1,
        TestTransitionScene1 = 2,
        TestTransitionScene2 = 3,
        TestSaveScene        = 4,
        TitleScene           = 5,
      }
    }
}
