//------------------------------------------------------------------------------
// This file is AUTO-GENERATED by OKGamesLib.SceneNameCodeGenerator.
//------------------------------------------------------------------------------
namespace OKGamesLib
{
    public static class SceneName {
      public enum SceneNameEnum {
        TestTransitionScene1 = 0,
        TestTransitionScene2 = 1,
        TestSaveScene        = 2,
        TitleScene           = 3,
      }
    }
}
