//------------------------------------------------------------------------------
// This file is AUTO-GENERATED by OKGamesLib.TagCodeGenerator.
//------------------------------------------------------------------------------
namespace OKGamesLib
{
    public static class Tag {
      public enum TagEnum {
        Untagged       = 0,
        Respawn        = 1,
        Finish         = 2,
        EditorOnly     = 3,
        MainCamera     = 4,
        Player         = 5,
        GameController = 6,
      }
    }
}
